ENABLE_LINTERS:
  - MAKEFILE_CHECKMAKE
  - MARKDOWN_MARKDOWNLINT
  - YAML_YAMLLINT
  - ACTION_ACTIONLINT
  - REPOSITORY_SEMGREP
  - REPOSITORY_GITLEAKS
DISABLE_LINTERS:
  - CSPELL_CSPELL

# Configuration for markdownlint
MARKDOWN_MARKDOWNLINT_CONFIG_FILE: .github/linters/.markdownlint.json