---
name: Create packages and test installation

on:
  pull_request:

jobs:
  centos7:
    name: Build CentOS 7 RPMs
    runs-on: ubuntu-latest
    container: quay.io/centos/centos:7
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install build requisites
        run: |
          yum install -y rpm-build rpmlint make rsync
      - name: build rpm
        run: |
          make rpm
          rpmlint --file .rpmlint.ini build/RPMS/x86_64/*.rpm
      - name: Upload rpms
        uses: actions/upload-artifact@v3
        with:
          name: rpms7
          path: |
            build/RPMS/x86_64/wn-*.el7.x86_64.rpm

  build-almalinux:
    strategy:
      matrix:
        almalinux-version: [8, 9]
    name: Build AlmaLinux ${{ matrix.almalinux-version }} RPMs
    runs-on: ubuntu-latest
    container: almalinux:${{ matrix.almalinux-version }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install build requisites
        run: |
          dnf install -y rpm-build rpmlint make rsync systemd-rpm-macros
      - name: build rpm
        run: |
          make clean rpm
          rpmlint --file .rpmlint.ini build/RPMS/x86_64/*.rpm
      - name: Upload RPMs
        uses: actions/upload-artifact@v3
        with:
          name: rpms${{ matrix.almalinux-version }}
          path: |
            build/RPMS/x86_64/wn-*.el${{ matrix.almalinux-version }}.x86_64.rpm

  centos7-install:
    name: Install CentOS 7 RPMs
    needs: centos7
    runs-on: ubuntu-latest
    container: quay.io/centos/centos:7
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: rpms7
      - name: Install generated RPMs
        run: |
          yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
          yum install -y http://repository.egi.eu/sw/production/umd/4/centos7/x86_64/updates/umd-release-4.1.3-1.el7.centos.noarch.rpm
          yum localinstall -y wn-*.rpm

  install-almalinux8:
    name: Install AlmaLinux 8 RPMs
    needs: build-almalinux
    runs-on: ubuntu-latest
    container: almalinux:8
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: rpms8
      - name: Install generated RPMs
        run: |
          # FIXME: add UMD5 when available
          dnf install -y epel-release
          dnf install -y https://ecsft.cern.ch/dist/cvmfs/cvmfs-release/cvmfs-release-latest.noarch.rpm
          dnf config-manager --set-enabled powertools
          dnf localinstall -y wn-*.rpm

  install-almalinux9:
    name: Install AlmaLinux 9 RPMs
    needs: build-almalinux
    runs-on: ubuntu-latest
    container: almalinux:9
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: rpms9
      - name: Install generated RPMs
        run: |
          # FIXME: add UMD5 when available
          dnf install -y epel-release
          dnf install -y https://ecsft.cern.ch/dist/cvmfs/cvmfs-release/cvmfs-release-latest.noarch.rpm
          dnf localinstall -y wn-*.rpm
