---
name: Create packages and test installation

on:
  pull_request:

jobs:
  build-almalinux:
    strategy:
      matrix:
        almalinux-version: [8, 9, 10]
    name: Build AlmaLinux ${{ matrix.almalinux-version }} RPMs
    runs-on: ubuntu-latest
    container: almalinux:${{ matrix.almalinux-version }}
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Install build requisites
        run: |
          dnf install -y almalinux-release-devel
          dnf install -y rpm-build rpmlint make rsync systemd-rpm-macros
      - name: build rpm
        run: |
          make clean rpm
          #rpmlint --file .rpmlint.ini build/RPMS/x86_64/*.rpm
      - name: Upload RPMs
        uses: actions/upload-artifact@v7
        with:
          name: rpms${{ matrix.almalinux-version }}
          path: |
            build/RPMS/x86_64/wn-*.el${{ matrix.almalinux-version }}.x86_64.rpm

  install-almalinux8:
    name: Install AlmaLinux 8 RPMs
    needs: build-almalinux
    runs-on: ubuntu-latest
    container: almalinux:8
    steps:
      - uses: actions/download-artifact@v8
        with:
          name: rpms8
      - name: Install generated RPMs
        run: |
          # FIXME: add UMD5 when available
          dnf install -y epel-release
          dnf install -y https://ecsft.cern.ch/dist/cvmfs/cvmfs-release/cvmfs-release-latest.noarch.rpm
          dnf config-manager --set-enabled powertools
          dnf localinstall -y x86_64/wn-*.rpm

  install-almalinux9:
    name: Install AlmaLinux 9 RPMs
    needs: build-almalinux
    runs-on: ubuntu-latest
    container: almalinux:9
    steps:
      - uses: actions/download-artifact@v8
        with:
          name: rpms9
      - name: Install generated RPMs
        run: |
          # FIXME: add UMD5 when available
          #dnf install -y epel-release
          #dnf install -y https://ecsft.cern.ch/dist/cvmfs/cvmfs-release/cvmfs-release-latest.noarch.rpm
          dnf-install -y https://repository.egi.eu/repository/umd/5/al9/release/x86_64/umd-release-5.0.0-1.al9.alma.noarch.rpm
          dnf localinstall -y x86_64/wn-*.rpm

  install-almalinux10:
    name: Install AlmaLinux 10 RPMs
    needs: build-almalinux
    runs-on: ubuntu-latest
    container: almalinux:10
    steps:
      - uses: actions/download-artifact@v8
        with:
          name: rpms9
      - name: Install generated RPMs
        run: |
          # FIXME: add UMD6 when available
          dnf install -y epel-release
          dnf install -y https://ecsft.cern.ch/dist/cvmfs/cvmfs-release/cvmfs-release-latest.noarch.rpm
          dnf localinstall -y x86_64/wn-*.rpm
