---
name: Lint

on: [pull_request]

jobs:
  lint:
    name: Static Checks
    runs-on: ubuntu-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          # Make sure the actual branch is checked out when running on PR
          ref: ${{ github.event.pull_request.head.sha }}
          # Full git history needed to get proper list of changed files
          fetch-depth: 0

      # Runs the MegaLinter action
      - name: Run Super-Linter on new changes
        uses: oxsecurity/megalinter@v9
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
